# Generated by Django 3.2.25 on 2024-06-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20240626_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AchivementCat',
            new_name='AchievementCat',
        ),
    ]
